# Generated by Django 4.1.7 on 2023-03-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_url',
            field=models.URLField(blank=True),
        ),
    ]
